#!/usr/bin/env node
/*
  Registers the Pinpoint native messaging host with every browser on this
  machine that can use it, on Windows and macOS.

  It writes:
    1. a launcher with the resolved node path baked in — browsers start the
       host with a bare environment, so `node` is rarely on their PATH
    2. two host manifests: Firefox allowlists an extension id, Chromium
       browsers allowlist an extension origin, and the formats differ
    3. the pointer each browser looks for — a registry value under HKCU on
       Windows, a file in the browser's NativeMessagingHosts folder on macOS

  Run:  npm run install-host
  Undo: npm run uninstall-host
*/
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { HOST_NAME, extensionIds } from '../scripts/ids.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const IS_WINDOWS = process.platform === 'win32';
const IS_MAC = process.platform === 'darwin';

if (!IS_WINDOWS && !IS_MAC) {
  console.error(`Pinpoint's native host supports Windows and macOS. This is ${process.platform}.`);
  console.error('The extension still works without it, saving through the browser\'s Downloads folder.');
  process.exit(1);
}

const DESCRIPTION = 'Pinpoint - writes region screenshots to disk and puts the notes bundle on the clipboard as a file';

/* Where each browser looks for the pointer. Windows keys live under HKCU;
   macOS paths live under ~/Library/Application Support. */
const support = path.join(os.homedir(), 'Library', 'Application Support');
const TARGETS = [
  { label: 'Firefox', flavour: 'firefox', key: 'Software\\Mozilla', dir: path.join(support, 'Mozilla'), always: true },
  { label: 'Chrome', flavour: 'chrome', key: 'Software\\Google\\Chrome', dir: path.join(support, 'Google', 'Chrome') },
  { label: 'Chromium', flavour: 'chrome', key: 'Software\\Chromium', dir: path.join(support, 'Chromium') },
  { label: 'Edge', flavour: 'chrome', key: 'Software\\Microsoft\\Edge', dir: path.join(support, 'Microsoft Edge') },
  { label: 'Brave', flavour: 'chrome', key: 'Software\\BraveSoftware\\Brave-Browser', dir: path.join(support, 'BraveSoftware', 'Brave-Browser') }
];

function resolveNode() {
  const flag = process.argv.indexOf('--node');
  if (flag > -1 && process.argv[flag + 1]) return process.argv[flag + 1];
  return process.execPath;   // whichever node is running this script
}

/* ------------------------------------------------------------------ launcher */

function writeLauncher(nodePath) {
  const hostScript = path.join(HERE, 'host.mjs');
  if (IS_WINDOWS) {
    const bat = path.join(HERE, 'pinpoint-host.bat');
    fs.writeFileSync(bat, [
      '@echo off',
      'rem Generated by install.mjs - launches the Pinpoint native messaging host.',
      `"${nodePath}" "%~dp0host.mjs"`,
      ''
    ].join('\r\n'), 'ascii');
    return bat;
  }
  const sh = path.join(HERE, 'pinpoint-host.sh');
  fs.writeFileSync(sh, [
    '#!/bin/sh',
    '# Generated by install.mjs - launches the Pinpoint native messaging host.',
    `exec "${nodePath}" "${hostScript}" "$@"`,
    ''
  ].join('\n'), 'utf8');
  fs.chmodSync(sh, 0o755);
  return sh;
}

/* ------------------------------------------------------------------ manifests */

function hostManifest(flavour, launcher, ids) {
  const base = { name: HOST_NAME, description: DESCRIPTION, path: launcher, type: 'stdio' };
  return flavour === 'firefox'
    ? { ...base, allowed_extensions: [ids.firefox] }
    : { ...base, allowed_origins: [`chrome-extension://${ids.chrome}/`] };
}

/* ------------------------------------------------------------------- register */

function registerWindows(target, manifestPath) {
  const key = `HKCU\\${target.key}\\NativeMessagingHosts\\${HOST_NAME}`;
  execFileSync('reg', ['add', key, '/ve', '/t', 'REG_SZ', '/d', manifestPath, '/f'], { stdio: 'ignore' });
  return key;
}

function registerMac(target, manifest) {
  const dir = path.join(target.dir, 'NativeMessagingHosts');
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, HOST_NAME + '.json');
  fs.writeFileSync(file, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  return file;
}

/* ------------------------------------------------------------------------ run */

const ids = extensionIds();
const nodePath = resolveNode();
if (!fs.existsSync(nodePath)) throw new Error(`node not found at ${nodePath}`);

const launcher = writeLauncher(nodePath);
console.log('launcher   ' + launcher);

const installed = [];
const skipped = [];

for (const target of TARGETS) {
  const manifest = hostManifest(target.flavour, launcher, ids);

  if (IS_WINDOWS) {
    // A registry value costs nothing if the browser is not installed, and it
    // is already there the day it is.
    const manifestPath = path.join(HERE, `manifest.${target.flavour}.json`);
    fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
    installed.push(`${target.label.padEnd(9)} ${registerWindows(target, manifestPath)}`);
    continue;
  }

  // On macOS the manifest has to live inside the browser's own folder, so
  // only touch browsers that are actually here.
  if (!target.always && !fs.existsSync(target.dir)) {
    skipped.push(target.label);
    continue;
  }
  installed.push(`${target.label.padEnd(9)} ${registerMac(target, manifest)}`);
}

for (const line of installed) console.log('registered ' + line);
if (skipped.length) console.log('skipped    ' + skipped.join(', ') + ' (not installed on this machine)');

console.log('');
console.log('Testing the host...');
execFileSync(nodePath, [path.join(HERE, 'test-host.mjs')], { stdio: 'inherit' });

console.log('');
console.log('Installed. Restart the browser, then open the Pinpoint popup:');
console.log('  the badge should read "host ready".');
